controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:                   
      type: joint_trajectory_controller/JointTrajectoryController

position_controllers:
  ros__parameters:
    joints:
      - hip1
      - thig1
      - shin1
      - hip2
      - thig2
      - shin2
      - hip3
      - thig3
      - shin3
      - hip4
      - thig4
      - shin4

    command_interfaces: [position]
    state_interfaces: [position]   


  
